# TOML results file for parKVFinder software

title = "parKVFinder results file"

[FILES_PATH]
INPUT = "/home/jvsguerra/remote-repos/kvfinder-ws/client/examples/1FMO.pdb"
OUTPUT = "/home/jvsguerra/remote-repos/kvfinder-ws/client/examples/9556742417561716475/output.KVFinder.output.pdb"

[PARAMETERS]
RESOLUTION = "Low"
STEP_SIZE = 0.6

[RESULTS.VOLUME]
KAA = 150.98
KAB = 42.77
KAC = 70.2
KAD = 5.18
KAE = 84.24
KAF = 12.31
KAG = 537.84
KAH = 17.28
KAI = 36.94
KAJ = 51.62
KAK = 39.96
KAL = 9.94
KAM = 99.58
KAN = 6.91
KAO = 24.84
KAP = 8.21
KAQ = 15.12

[RESULTS.AREA]
KAA = 121.12
KAB = 50.89
KAC = 65.04
KAD = 10.04
KAE = 115.3
KAF = 22.11
KAG = 474.15
KAH = 35.4
KAI = 49.6
KAJ = 62.14
KAK = 56.12
KAL = 20.4
KAM = 111.94
KAN = 12.1
KAO = 31.13
KAP = 17.47
KAQ = 20.87

[RESULTS.RESIDUES]
KAA = [ [ "306", "E", "Y",], [ "14", "E", "S",], [ "15", "E", "V",], [ "18", "E", "F",], [ "19", "E", "L",], [ "100", "E", "F",], [ "152", "E", "L",], [ "155", "E", "E",], [ "156", "E", "Y",], [ "292", "E", "K",], [ "302", "E", "W",], [ "303", "E", "I",],]
KAB = [ [ "156", "E", "Y",], [ "18", "E", "F",], [ "22", "E", "A",], [ "25", "E", "D",], [ "26", "E", "F",], [ "29", "E", "K",], [ "97", "E", "A",], [ "98", "E", "V",], [ "99", "E", "N",],]
KAC = [ [ "313", "E", "P",], [ "141", "E", "P",], [ "142", "E", "H",], [ "144", "E", "R",], [ "145", "E", "F",], [ "148", "E", "A",], [ "299", "E", "T",], [ "300", "E", "T",], [ "305", "E", "I",], [ "310", "E", "V",], [ "311", "E", "E",],]
KAD = [ [ "322", "E", "G",], [ "122", "E", "Y",], [ "124", "E", "A",], [ "176", "E", "Q",], [ "318", "E", "F",], [ "320", "E", "G",],]
KAE = [ [ "308", "E", "R",], [ "95", "E", "L",], [ "96", "E", "Q",], [ "97", "E", "A",], [ "98", "E", "V",], [ "99", "E", "N",], [ "100", "E", "F",], [ "101", "E", "P",], [ "103", "E", "L",], [ "104", "E", "V",], [ "105", "E", "K",], [ "106", "E", "L",], [ "121", "E", "E",], [ "122", "E", "Y",], [ "123", "E", "V",], [ "124", "E", "A",], [ "125", "E", "G",], [ "175", "E", "D",], [ "176", "E", "Q",], [ "181", "E", "Q",],]
KAF = [ [ "109", "E", "S",], [ "34", "E", "S",], [ "37", "E", "T",], [ "96", "E", "Q",], [ "106", "E", "L",], [ "107", "E", "E",], [ "108", "E", "F",],]
KAG = [ [ "327", "E", "F",], [ "49", "E", "L",], [ "50", "E", "G",], [ "51", "E", "T",], [ "52", "E", "G",], [ "53", "E", "S",], [ "54", "E", "F",], [ "55", "E", "G",], [ "56", "E", "R",], [ "57", "E", "V",], [ "70", "E", "A",], [ "72", "E", "K",], [ "74", "E", "L",], [ "84", "E", "Q",], [ "87", "E", "H",], [ "88", "E", "T",], [ "91", "E", "E",], [ "104", "E", "V",], [ "120", "E", "M",], [ "121", "E", "E",], [ "122", "E", "Y",], [ "123", "E", "V",], [ "127", "E", "E",], [ "166", "E", "D",], [ "168", "E", "K",], [ "170", "E", "E",], [ "171", "E", "N",], [ "173", "E", "L",], [ "183", "E", "T",], [ "184", "E", "D",], [ "186", "E", "G",], [ "187", "E", "F",], [ "200", "E", "G",], [ "201", "E", "T",],]
KAH = [ [ "314", "E", "F",], [ "131", "E", "H",], [ "138", "E", "F",], [ "142", "E", "H",], [ "146", "E", "Y",], [ "174", "E", "I",],]
KAI = [ [ "350", "E", "F",], [ "33", "E", "P",], [ "89", "E", "L",], [ "92", "E", "K",], [ "93", "E", "R",], [ "96", "E", "Q",], [ "349", "E", "E",],]
KAJ = [ [ "330", "E", "Y",], [ "49", "E", "L",], [ "126", "E", "G",], [ "127", "E", "E",], [ "129", "E", "F",], [ "130", "E", "S",], [ "326", "E", "N",], [ "327", "E", "F",], [ "328", "E", "D",],]
KAK = [ [ "336", "E", "R",], [ "51", "E", "T",], [ "55", "E", "G",], [ "56", "E", "R",], [ "73", "E", "I",], [ "74", "E", "L",], [ "75", "E", "D",], [ "115", "E", "N",], [ "335", "E", "I",],]
KAL = [ [ "217", "E", "K",], [ "163", "E", "I",], [ "191", "E", "V",], [ "193", "E", "G",], [ "195", "E", "T",], [ "215", "E", "Y",], [ "216", "E", "N",],]
KAM = [ [ "223", "E", "A",], [ "165", "E", "R",], [ "166", "E", "D",], [ "167", "E", "L",], [ "199", "E", "C",], [ "200", "E", "G",], [ "201", "E", "T",], [ "204", "E", "Y",], [ "205", "E", "L",], [ "206", "E", "A",], [ "209", "E", "I",], [ "219", "E", "V",], [ "220", "E", "D",], [ "222", "E", "W",],]
KAN = [ [ "331", "E", "E",], [ "48", "E", "T",], [ "51", "E", "T",], [ "56", "E", "R",], [ "330", "E", "Y",],]
KAO = [ [ "273", "E", "L",], [ "222", "E", "W",], [ "238", "E", "F",], [ "253", "E", "G",], [ "254", "E", "K",], [ "255", "E", "V",],]
KAP = [ [ "256", "E", "R",], [ "229", "E", "Y",], [ "237", "E", "P",], [ "238", "E", "F",], [ "249", "E", "K",], [ "254", "E", "K",], [ "255", "E", "V",],]
KAQ = [ [ "277", "E", "L",], [ "207", "E", "P",], [ "208", "E", "E",], [ "211", "E", "L",], [ "213", "E", "K",], [ "275", "E", "V",],]
